### ISSUE TITLE
Support addon chains like ShaguTweaks + ShaguTweaks-Mods

### ISSUE THREAD

**Issue by refaim** [refaim/snapjaw#12]

**Comment by GryllsAddons** [comment]
I've changed ShaguTweaks-Mods to be a seperate addon with a ShaguTweaks dependency (was looking at compatibility with Woblight's addon manager) so should make things easier. This may still be helpful for other addons however!

**Comment by refaim** [comment]
@GryllsAddons 

Thanks! That's good to know :)

I don't know of any other addons with similar distribution scheme. Do you?

Now I'm more interested in trying to finish https://github.com/refaim/Vanilla-WoW-Lua-Definitions, so maybe some other time.

**Comment by GryllsAddons** [comment]
The only one that comes to mind is if you want to install [Atlas](https://github.com/laytya/Atlas) (which contains multiple Atlas addons together) then you want to add [Turtle AtlasLoot](https://github.com/Lexiebean/AtlasLoot) on top. I think this issue would be rare though - probably not worth spending your time on when you have other more interesting things to work on :)
